Fixed sonar issues in identity-outbound-auth-tiqr
wso2-extensions/identity-outbound-auth-tiqr pull request #3
Opened 2017-07-17 13:11 UTC by supunharsha

2017-07-17 18:47 UTC, omindu requested changes

2017-07-17 18:47 UTC, omindu commented on component/authentication-endpoint/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/tiqr/QRCode.java
> +            if(connection != null){
Formatting issue `if(connection != null) {`

2017-07-17 18:47 UTC, omindu commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/tiqr/TiqrAuthenticator.java
> +            if(connection != null){
Formatting issue `if(connection != null) {`

2017-07-25 06:44 UTC, madumalt commented on component/authentication-endpoint/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/tiqr/QRCode.java
> +            if (connection != null) {
can't we go with, "try with" here?

2017-07-25 06:44 UTC, madumalt commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/tiqr/TiqrAuthenticator.java
> +            if (connection != null) {
can't we go with, "try with" here?

2017-07-26 03:29 UTC, supunharsha commented on component/authentication-endpoint/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/tiqr/QRCode.java
> +            if (connection != null) {
HttpURLConnection is not extends from AutoClosable interface, so we can't use it with try with resource.

2017-07-26 03:33 UTC, supunharsha commented on component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/tiqr/TiqrAuthenticator.java
> +            if (connection != null) {
HttpURLConnection is not implements from AutoClosable interface, so we can't use it with try with resource.

2017-07-31 15:30 UTC, rushmin approved these changes

2017-07-31 21:03 UTC, omindu approved these changes

2017-08-02 05:31 UTC, merged